# prelude = "prelude"

[[articles]]
name = "philosophy"
title = "The Philosophy"

[[articles]]
name = "lang"
title = "The Language"

[[articles]]
name = "builtin"
title = "The Builtin Module"

[[articles]]
name = "editor"
title = "The Editor Module"

[[articles]]
name = "embedded"
title = "Embedded Modules"
