[[articles]]
name = "philosophy"
title = "The Philosophy"

[[articles]]
name = "language"
title = "The Language"

[[articles]]
name = "builtin"
title = "The Builtin Module"

[[articles]]
name = "edit"
title = "The Editor Module (edit:) (WIP)"

[[articles]]
name = "re"
title = "The Regular Expression Module (re:) (WIP)"

[[articles]]
name = "embedded"
title = "Embedded Modules"
