# prelude = "prelude"

[[articles]]
name = "philosophy"
title = "The Philosophy"

[[articles]]
name = "lang"
title = "The Language"

[[articles]]
name = "builtin"
title = "The Builtin Module"

[[articles]]
name = "le"
title = "The Editor API"

[[articles]]
name = "bundled"
title = "The Bundled Modules"
