title = "Elvish the Shell"
author = "Qi Xiao"
feedPosts = 10
template = "template.html"

[index]
name = "home"
title = "Home"

[[categories]]
name = "download"
title = "Download"

[[categories]]
name = "learn"
title = "Learn"

[[categories]]
name = "ref"
title = "Reference"

[[categories]]
name = "blog"
title = "Blog"
