title = "Elvish: Friendly and Expressive Shell"
author = "Qi Xiao"
feedPosts = 10
template = "template.html"
rootURL = "https://elvish.io"

[index]
name = "home"
title = "Home"

[[categories]]
name = "download"
title = "Download"

[[categories]]
name = "blog"
title = "Blog"

[[categories]]
name = "learn"
title = "Learn"

[[categories]]
name = "ref"
title = "Reference"
